In [1]:
import numpy as np

In [2]:
#creating an array
arr=np.array((1,2,3,4,5))

In [3]:
arr

array([1, 2, 3, 4, 5])

In [5]:
#datatype of an array
arr=np.array([1,2,3,4],dtype=float)

In [6]:
arr

array([1., 2., 3., 4.])

In [7]:
#datatype of an array
arr=np.array([],dtype='S')

In [21]:
arr=arr.astype(int)

In [8]:
arr

array([], dtype='|S1')

In [13]:
#print the element starting from 10 to 40 and skiping 2 elements
arr=np.arange(10,40,2)

In [14]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [16]:
#to insert the element in the array
np.insert(arr,5,int(40))

array([10, 12, 14, 16, 18, 40, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [17]:
#to delete the element in the array
np.delete(arr,5)

array([10, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [18]:
#insert element at the given index
arr=np.insert(arr,0,100)

In [19]:
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [20]:
#add the element at the last
arr=np.append(arr,50)
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38,  50])

In [22]:
#matrices

In [23]:
mat=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])

In [24]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
#to get the elements of a matrix
mat[1,1]

6

In [33]:
#speed list
a=[i for i in range(10000000)]
b=[i for i in range (10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

4.737594127655029


In [35]:
arr1=np.arange(10000000)
arr2=np.arange(10000000,20000000)
import time
start=time.time()
c=arr1+arr2
print(time.time()-start)

0.046875953674316406


In [29]:
5.4958319664001465/0.18978261947631836


28.958563126408595

In [38]:
#to get the elements of a fixed column
for i in range(3):
    print(mat[i,1])

2
6
10


In [39]:
d3=np.array([[[1,2,3,4],[5,6,7,8,]],[[9,10,11,12],[13,14,15,16]]])

In [43]:
d3[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
d3[1,0]

array([ 9, 10, 11, 12])

In [45]:
d3[1,0,1]

10

In [1]:
dn=np.array([3],ndarray=5)

NameError: name 'np' is not defined

In [ ]:
https://github.com/Samantsaini/learning-ML

In [ ]:
#rotating an array by kth position
def rotate(arr,n,k):
    k=k%n
    for i in range(k):
        t=arr[n-1]
        for j in range(n-1,0,-1):
            arr[j]=arr[j-1]
        arr[0]=t
    return arr